### ISSUE TITLE
can't write to hdfs with webhdfs

### ISSUE THREAD

**Issue by nickchang** [fluent/fluent-plugin-webhdfs#14]
Hadoop Version is 2.4

My config:
<source>
  type tail
  format apache
  path /var/log/httpd/sharebook_lab/booklab_feed_https_%Y%m%d.log
  tag td.apache.access
</source>

<match td.*.*>
  type geoip
  geoip_lookup_key host
  <record>
    city            ${city['host']}
    latitude        ${latitude['host']}
    longitude       ${longitude['host']}
    country_code3   ${country_code3['host']}
    country         ${country_code['host']}
    country_name    ${country_name['host']}
    dma             ${dma_code['host']}
    area            ${area_code['host']}
    region          ${region['host']}
  </record>
  remove_tag_prefix td.
  add_tag_prefix hdfs.
</match>

<match hdfs.*.*>
  type webhdfs
  host 10.1.3.10
  port 50070
  path /hdfs/feed_access_%Y%m%d_%H.log
</match>

2014-04-25 17:23:40 +0800 [warn]: failed to communicate hdfs cluster, path: /hdfs/feed_access_20140425_15.log
2014-04-25 17:23:40 +0800 [warn]: temporarily failed to flush the buffer. next_retry=2014-04-25 18:34:08 +0800 error_class="SocketError" error="getaddrinfo: Name or service not known" instance=70012279940460
  2014-04-25 17:23:40 +0800 [warn]: /usr/lib64/fluent/ruby/lib/ruby/1.9.1/net/http.rb:763:in `initialize'
  2014-04-25 17:23:40 +0800 [warn]: /usr/lib64/fluent/ruby/lib/ruby/1.9.1/net/http.rb:763:in`open'
  2014-04-25 17:23:40 +0800 [warn]: /usr/lib64/fluent/ruby/lib/ruby/1.9.1/net/http.rb:763:in `block in connect'
  2014-04-25 17:23:40 +0800 [warn]: /usr/lib64/fluent/ruby/lib/ruby/1.9.1/timeout.rb:69:in`timeout'
  2014-04-25 17:23:40 +0800 [warn]: /usr/lib64/fluent/ruby/lib/ruby/1.9.1/timeout.rb:100:in `timeout'
  2014-04-25 17:23:40 +0800 [warn]: /usr/lib64/fluent/ruby/lib/ruby/1.9.1/net/http.rb:763:in`connect'
  2014-04-25 17:23:40 +0800 [warn]: /usr/lib64/fluent/ruby/lib/ruby/1.9.1/net/http.rb:756:in `do_start'
  2014-04-25 17:23:40 +0800 [warn]: /usr/lib64/fluent/ruby/lib/ruby/1.9.1/net/http.rb:745:in`start'
  2014-04-25 17:23:40 +0800 [warn]: /usr/lib64/fluent/ruby/lib/ruby/1.9.1/net/http.rb:1285:in `request'
  2014-04-25 17:23:40 +0800 [warn]: /usr/lib64/fluent/ruby/lib/ruby/1.9.1/net/http.rb:1265:in`send_request'
  2014-04-25 17:23:40 +0800 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/webhdfs-0.5.5/lib/webhdfs/client_v1.rb:281:in `request'
  2014-04-25 17:23:40 +0800 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/webhdfs-0.5.5/lib/webhdfs/client_v1.rb:242:in`operate_requests'
  2014-04-25 17:23:40 +0800 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/webhdfs-0.5.5/lib/webhdfs/client_v1.rb:45:in `create'
  2014-04-25 17:23:40 +0800 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluent-plugin-webhdfs-0.2.2/lib/fluent/plugin/out_webhdfs.rb:189:in`rescue in send_data'
  2014-04-25 17:23:40 +0800 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluent-plugin-webhdfs-0.2.2/lib/fluent/plugin/out_webhdfs.rb:186:in `send_data'
  2014-04-25 17:23:40 +0800 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluent-plugin-webhdfs-0.2.2/lib/fluent/plugin/out_webhdfs.rb:205:in`write'
  2014-04-25 17:23:40 +0800 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.45/lib/fluent/buffer.rb:296:in `write_chunk'
  2014-04-25 17:23:40 +0800 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.45/lib/fluent/buffer.rb:276:in`pop'
  2014-04-25 17:23:40 +0800 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.45/lib/fluent/output.rb:310:in `try_flush'
  2014-04-25 17:23:40 +0800 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.45/lib/fluent/output.rb:132:in`run'

**Comment by wpengcheng** [comment]
@nickchang ,
How do you include include slave's IP or hostname
