### ISSUE TITLE
Unable to close file because the last block does not have enough number of replicas.

### ISSUE THREAD

**Issue by loveshell** [fluent/fluent-plugin-webhdfs#18]
HI guys,

Recently we are seeing the error above quite regularly, it seems this is failing to flush the buffer as it is trying to create a file with a name, which has already been created on HDFS.
and 
http://stackoverflow.com/questions/24366490/use-fluent-to-collect-data-and-append-to-hdfs-throw-the-alreadybeingcreatedexce
and now i can't write to hdfs

Error is as follows

```
2014-08-20 19:30:29 +0800 [warn]: failed to communicate hdfs cluster, path: /weblog/access/day=20140820/localhost.log
2014-08-20 19:30:29 +0800 [warn]: temporarily failed to flush the buffer. next_retry=2014-08-20 19:30:04 +0800 error_class="WebHDFS::IOError" error="{\"RemoteException\":{\"exception\":\"IOException\",\"javaClassName\":\"java.io.IOException\",\"message\":\"Unable to close file because the last block does not have enough number of replicas.\"}}" instance=69823638713360
  2014-08-20 19:30:29 +0800 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/webhdfs-0.5.5/lib/webhdfs/client_v1.rb:317:in `request'
  2014-08-20 19:30:29 +0800 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/webhdfs-0.5.5/lib/webhdfs/client_v1.rb:242:in `operate_requests'
  2014-08-20 19:30:29 +0800 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/webhdfs-0.5.5/lib/webhdfs/client_v1.rb:56:in `append'
  2014-08-20 19:30:29 +0800 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluent-plugin-webhdfs-0.2.2/lib/fluent/plugin/out_webhdfs.rb:187:in `send_data'
  2014-08-20 19:30:29 +0800 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluent-plugin-webhdfs-0.2.2/lib/fluent/plugin/out_webhdfs.rb:205:in `write'
  2014-08-20 19:30:29 +0800 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.50/lib/fluent/buffer.rb:296:in `write_chunk'
  2014-08-20 19:30:29 +0800 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.50/lib/fluent/buffer.rb:276:in `pop'
  2014-08-20 19:30:29 +0800 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.50/lib/fluent/output.rb:310:in `try_flush'
  2014-08-20 19:30:29 +0800 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.50/lib/fluent/output.rb:132:in `run'
2014-08-20 19:30:29 +0800 [warn]: failed to communicate hdfs cluster, path: /weblog/access/day=20140820/localhost.log
2014-08-20 19:30:29 +0800 [warn]: temporarily failed to flush the buffer. next_retry=2014-08-20 19:30:05 +0800 error_class="WebHDFS::IOError" error="{\"RemoteException\":{\"exception\":\"AlreadyBeingCreatedException\",\"javaClassName\":\"org.apache.hadoop.hdfs.protocol.AlreadyBeingCreatedException\",\"message\":\"Failed to create file [/weblog/access/day=20140820/localhost.log] for [DFSClient_NONMAPREDUCE_-1338562566_570303] on client [192.168.166.203], because this file is already being created by [DFSClient_NONMAPREDUCE_2086608883_519513] on [192.168.166.210]\\n\\tat org.apache.hadoop.hdfs.server.namenode.FSNamesystem.recoverLeaseInternal(FSNamesystem.java:2534)\\n\\tat org.apache.hadoop.hdfs.server.namenode.FSNamesystem.appendFileInternal(FSNamesystem.java:2369)\\n\\tat org.apache.hadoop.hdfs.server.namenode.FSNamesystem.appendFileInt(FSNamesystem.java:2598)\\n\\tat org.apache.hadoop.hdfs.server.namenode.FSNamesystem.appendFile(FSNamesystem.java:2561)\\n\\tat org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.append(NameNodeRpcServer.java:522)\\n\\tat org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.append(ClientNamenodeProtocolServerSideTranslatorPB.java:373)\\n\\tat org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)\\n\\tat org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:585)\\n\\tat org.apache.hadoop.ipc.RPC$Server.call(RPC.java:1026)\\n\\tat org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:1986)\\n\\tat org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:1982)\\n\\tat java.security.AccessController.doPrivileged(Native Method)\\n\\tat javax.security.auth.Subject.doAs(Subject.java:415)\\n\\tat org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1548)\\n\\tat org.apache.hadoop.ipc.Server$Handler.run(Server.java:1980)\\n\"}}" instance=69823638713360
  2014-08-20 19:30:29 +0800 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/webhdfs-0.5.5/lib/webhdfs/client_v1.rb:317:in `request'
  2014-08-20 19:30:29 +0800 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/webhdfs-0.5.5/lib/webhdfs/client_v1.rb:242:in `operate_requests'
  2014-08-20 19:30:29 +0800 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/webhdfs-0.5.5/lib/webhdfs/client_v1.rb:56:in `append'
  2014-08-20 19:30:29 +0800 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluent-plugin-webhdfs-0.2.2/lib/fluent/plugin/out_webhdfs.rb:187:in `send_data'
  2014-08-20 19:30:29 +0800 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluent-plugin-webhdfs-0.2.2/lib/fluent/plugin/out_webhdfs.rb:205:in `write'
  2014-08-20 19:30:29 +0800 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.50/lib/fluent/buffer.rb:296:in `write_chunk'
  2014-08-20 19:30:29 +0800 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.50/lib/fluent/buffer.rb:276:in `pop'
  2014-08-20 19:30:29 +0800 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.50/lib/fluent/output.rb:310:in `try_flush'
  2014-08-20 19:30:29 +0800 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.50/lib/fluent/output.rb:132:in `run'
2014-08-20 19:30:29 +0800 [warn]: failed to communicate hdfs cluster, path: /weblog/access/day=20140820/localhost.log
2014-08-20 19:30:29 +0800 [warn]: temporarily failed to flush the buffer. next_retry=2014-08-20 19:30:09 +0800 error_class="WebHDFS::IOError" error="{\"RemoteException\":{\"exception\":\"AlreadyBeingCreatedException\",\"javaClassName\":\"org.apache.hadoop.hdfs.protocol.AlreadyBeingCreatedException\",\"message\":\"Failed to create file [/weblog/access/day=20140820/localhost.log] for [DFSClient_NONMAPREDUCE_318222613_675838] on client [192.168.166.209], because this file is already being created by [DFSClient_NONMAPREDUCE_2086608883_519513] on [192.168.166.210]\\n\\tat org.apache.hadoop.hdfs.server.namenode.FSNamesystem.recoverLeaseInternal(FSNamesystem.java:2534)\\n\\tat org.apache.hadoop.hdfs.server.namenode.FSNamesystem.appendFileInternal(FSNamesystem.java:2369)\\n\\tat org.apache.hadoop.hdfs.server.namenode.FSNamesystem.appendFileInt(FSNamesystem.java:2598)\\n\\tat org.apache.hadoop.hdfs.server.namenode.FSNamesystem.appendFile(FSNamesystem.java:2561)\\n\\tat org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.append(NameNodeRpcServer.java:522)\\n\\tat org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.append(ClientNamenodeProtocolServerSideTranslatorPB.java:373)\\n\\tat org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)\\n\\tat org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:585)\\n\\tat org.apache.hadoop.ipc.RPC$Server.call(RPC.java:1026)\\n\\tat org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:1986)\\n\\tat org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:1982)\\n\\tat java.security.AccessController.doPrivileged(Native Method)\\n\\tat javax.security.auth.Subject.doAs(Subject.java:415)\\n\\tat org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1548)\\n\\tat org.apache.hadoop.ipc.Server$Handler.run(Server.java:1980)\\n\"}}" instance=69823638713360
  2014-08-20 19:30:29 +0800 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/webhdfs-0.5.5/lib/webhdfs/client_v1.rb:317:in `request'
  2014-08-20 19:30:29 +0800 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/webhdfs-0.5.5/lib/webhdfs/client_v1.rb:242:in `operate_requests'
  2014-08-20 19:30:29 +0800 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/webhdfs-0.5.5/lib/webhdfs/client_v1.rb:56:in `append'
  2014-08-20 19:30:29 +0800 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluent-plugin-webhdfs-0.2.2/lib/fluent/plugin/out_webhdfs.rb:187:in `send_data'
  2014-08-20 19:30:29 +0800 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluent-plugin-webhdfs-0.2.2/lib/fluent/plugin/out_webhdfs.rb:205:in `write'
  2014-08-20 19:30:29 +0800 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.50/lib/fluent/buffer.rb:296:in `write_chunk'
  2014-08-20 19:30:29 +0800 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.50/lib/fluent/buffer.rb:276:in `pop'
  2014-08-20 19:30:29 +0800 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.50/lib/fluent/output.rb:310:in `try_flush'
  2014-08-20 19:30:29 +0800 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.50/lib/fluent/output.rb:132:in `run'
2014-08-20 19:30:29 +0800 [warn]: failed to communicate hdfs cluster, path: /weblog/access/day=20140820/localhost.log
2014-08-20 19:30:29 +0800 [warn]: temporarily failed to flush the buffer. next_retry=2014-08-20 19:30:18 +0800 error_class="WebHDFS::IOError" error="{\"RemoteException\":{\"exception\":\"AlreadyBeingCreatedException\",\"javaClassName\":\"org.apache.hadoop.hdfs.protocol.AlreadyBeingCreatedException\",\"message\":\"Failed to create file [/weblog/access/day=20140820/localhost.log] for [DFSClient_NONMAPREDUCE_-291834276_570303] on client [192.168.166.203], because this file is already being created by [DFSClient_NONMAPREDUCE_2086608883_519513] on [192.168.166.210]\\n\\tat org.apache.hadoop.hdfs.server.namenode.FSNamesystem.recoverLeaseInternal(FSNamesystem.java:2534)\\n\\tat org.apache.hadoop.hdfs.server.namenode.FSNamesystem.appendFileInternal(FSNamesystem.java:2369)\\n\\tat org.apache.hadoop.hdfs.server.namenode.FSNamesystem.appendFileInt(FSNamesystem.java:2598)\\n\\tat org.apache.hadoop.hdfs.server.namenode.FSNamesystem.appendFile(FSNamesystem.java:2561)\\n\\tat org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.append(NameNodeRpcServer.java:522)\\n\\tat org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.append(ClientNamenodeProtocolServerSideTranslatorPB.java:373)\\n\\tat org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)\\n\\tat org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:585)\\n\\tat org.apache.hadoop.ipc.RPC$Server.call(RPC.java:1026)\\n\\tat org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:1986)\\n\\tat org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:1982)\\n\\tat java.security.AccessController.doPrivileged(Native Method)\\n\\tat javax.security.auth.Subject.doAs(Subject.java:415)\\n\\tat org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1548)\\n\\tat org.apache.hadoop.ipc.Server$Handler.run(Server.java:1980)\\n\"}}" instance=69823638713360
```

**Comment by tagomoris** [comment]
Original post seems to write the same log file from several servers.
About 2nd comment, one datanode cannot satisfy replication factor. So it's configuration problem of hadoop clusters.

**Comment by binarymechanic** [comment]
I've gotten the error to, after increasing the namenode dfs.namenode.handler.count attribute.  Did you ever resolve this?

**Comment by asdf2014** [comment]
@tagomoris How to fix the problem about configuration? Please show the method.

**Comment by asdf2014** [comment]
Fixed, after i change the value of <dfs.replication>, thx :+1:

**Comment by asdf2014** [comment]
Fixed, after i change the value of "dfs.replication", thx :+1:

**Comment by tagomoris** [comment]
:+1:

**Comment by imperio-wxm** [comment]
@asdf2014 @loveshell @tagomoris 

I got same error.How do you fixed it?
My cluster default vlaue "dfs.replication=3" in hdfs-site.xml.
If I set "dfs.replication=1",I am afraid there will be the risk of losing data.

**Comment by VennilaJ** [comment]
I am facing the same issue. Can anyone please help me.

2018-02-20 07:58:22,428 WARN  [Thread-12515] hdfs.DFSClient: DataStreamer Exception
java.lang.NullPointerException
	at sun.nio.ch.EPollArrayWrapper.isEventsHighKilled(EPollArrayWrapper.java:174)
	at sun.nio.ch.EPollArrayWrapper.setUpdateEvents(EPollArrayWrapper.java:190)
	at sun.nio.ch.EPollArrayWrapper.add(EPollArrayWrapper.java:239)
	at sun.nio.ch.EPollSelectorImpl.implRegister(EPollSelectorImpl.java:178)
	at sun.nio.ch.SelectorImpl.register(SelectorImpl.java:132)
	at java.nio.channels.spi.AbstractSelectableChannel.register(AbstractSelectableChannel.java:212)
	at java.nio.channels.SelectableChannel.register(SelectableChannel.java:280)
	at org.apache.hadoop.net.SocketIOWithTimeout$SelectorPool.select(SocketIOWithTimeout.java:334)
	at org.apache.hadoop.net.SocketIOWithTimeout.connect(SocketIOWithTimeout.java:203)
	at org.apache.hadoop.net.NetUtils.connect(NetUtils.java:529)
	at org.apache.hadoop.hdfs.DFSOutputStream.createSocketForPipeline(DFSOutputStream.java:1526)
	at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.createBlockOutputStream(DFSOutputStream.java:1328)
	at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.nextBlockOutputStream(DFSOutputStream.java:1281)
	at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.run(DFSOutputStream.java:526)




2018-02-20 07:59:24,521 WARN  [rs()-flush-proc-pool1578-thread-1] 
regionserver.HStore: Failed flushing store file, retrying num=0
java.io.IOException: Unable to close file because the last block does not have enough number of replicas.
	at org.apache.hadoop.hdfs.DFSOutputStream.completeFile(DFSOutputStream.java:2151)
	at org.apache.hadoop.hdfs.DFSOutputStream.close(DFSOutputStream.java:2119)
	at org.apache.hadoop.fs.FSDataOutputStream$PositionCache.close(FSDataOutputStream.java:72)
	at org.apache.hadoop.fs.FSDataOutputStream.close(FSDataOutputStream.java:106)
	at org.apache.hadoop.hbase.io.hfile.AbstractHFileWriter.finishClose(AbstractHFileWriter.java:248)
	at org.apache.hadoop.hbase.io.hfile.HFileWriterV3.finishClose(HFileWriterV3.java:133)
	at org.apache.hadoop.hbase.io.hfile.HFileWriterV2.close(HFileWriterV2.java:380)
	at org.apache.hadoop.hbase.regionserver.StoreFile$Writer.close(StoreFile.java:1113)
	at org.apache.hadoop.hbase.regionserver.StoreFlusher.finalizeWriter(StoreFlusher.java:72)
	at org.apache.hadoop.hbase.regionserver.DefaultStoreFlusher.flushSnapshot(DefaultStoreFlusher.java:84)
	at org.apache.hadoop.hbase.regionserver.HStore.flushCache(HStore.java:936)
	at org.apache.hadoop.hbase.regionserver.HStore$StoreFlusherImpl.flushCache(HStore.java:2413)
	at org.apache.hadoop.hbase.regionserver.HRegion.internalFlushCacheAndCommit(HRegion.java:2456)
	at org.apache.hadoop.hbase.regionserver.HRegion.internalFlushcache(HRegion.java:2186)
	at org.apache.hadoop.hbase.regionserver.HRegion.internalFlushcache(HRegion.java:2148)
	at org.apache.hadoop.hbase.regionserver.HRegion.flushcache(HRegion.java:2039)
	at org.apache.hadoop.hbase.regionserver.HRegion.flush(HRegion.java:1965)
	at org.apache.hadoop.hbase.procedure.flush.FlushTableSubprocedure$RegionFlushTask.call(FlushTableSubprocedure.java:68)
	at org.apache.hadoop.hbase.procedure.flush.FlushTableSubprocedure$RegionFlushTask.call(FlushTableSubprocedure.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by datianshi21** [comment]
Same issue, can someone help me?

**Comment by yangsong1993** [comment]
Same issue
