### ISSUE TITLE
httpFS - Do not create file if it does not exist

### ISSUE THREAD

**Issue by hurtauda** [fluent/fluent-plugin-webhdfs#46]
Hello,

We are running a MapR custer and webHDFS is not supported by MapR. So we are trying to populate hadoop using httpFS.

Our Webhdfs config :
```
  @type webhdfs
  host mapr-mapr-master-0
  port 14000
  path "/uhalogs/docker/docker-%M.log"
  time_slice_format %M
  flush_interval 5s
  username mapr
  httpfs true
```

However when using the fluentd plugin, logs are appended correclty to an existing file. But if the file does not exist (using a timestamp-based filename), we get a WebHDFS::ServerError instead of a WebHDFS::FileNotFoundError that would create the file I guess.

Error 500 received by Mapr :
```
{
  "RemoteException": {
    "message": "Append failed for file: /uhalogs/docker/testfile.log, error: No such file or directory (2)",
    "exception": "IOException",
    "javaClassName": "java.io.IOException"
  }
}
```

logs by fluentd-webhdfs plugin :
```
2017-01-12 13:59:09 +0000 [warn]: failed to communicate hdfs cluster, path: /uhalogs/docker/docker-58.log
2017-01-12 13:59:09 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2017-01-12 14:00:13 +0000 error_class="WebHDFS::ServerError" error="{\"RemoteException\":{\"message\":\"Append failed for file: \\/uhalogs\\/docker\\/docker-58.log, error: No such file or directory (2)\",\"exception\":\"IOException\",\"javaClassName\":\"java.io.IOException\"}}" plugin_id="object:3fe5f920c960"
2017-01-12 13:59:09 +0000 [warn]: suppressed same stacktrace
```

related code :
[https://github.com/fluent/fluent-plugin-webhdfs/blob/master/lib/fluent/plugin/out_webhdfs.rb#L262](url)

What I am not sure and I can't find proper specifications for HttpFS on the web is :
- Is it a bad implementation of httpFS on MapR side or should we handle this exception as well on the fluentd plugin ?

Thank You
Alban

**Comment by enarciso** [comment]
I'm also experiencing this problem but on the cloudera platform. We cannot use webhdfs because it does not have HA capabilities compared to httpfs.

**Comment by repeatedly** [comment]
Sorry for missing this issue.
I'm not familiar with HttpFS but if the WebHDFS and HttpFS are incompatibile in several operations, we should care it.

> Is it a bad implementation of httpFS on MapR side 

From enarciso comment, it seems HttpFS behaviour is same on several distribution. I'm not sure this is a bug of HttpFS or not.
I think `append` operation should create new file when file doesn't exist.

**Comment by enarciso** [comment]
My unfortunate workaround at the moment is to constantly monitor the httpfs logs, watch for string like above and run a `touchz` to create the file. Thank you for look into this @repeatedly

**Comment by tagomoris** [comment]
`WebHDFS::ServerError` means that the client (fluentd) receives HTTP response code 500 from HttpFs server. WebHDFS server returns 404 for such cases.
IMO it's a bug of HttpFs implementation, because of behavior incompatibility between WebHDFS and HttpFs.

> And it (HttpFs) is interoperable with the webhdfs REST HTTP API.
https://hadoop.apache.org/docs/r2.8.0/hadoop-hdfs-httpfs/index.html

**Comment by enarciso** [comment]
Thank you @tagomoris, ive open a case with Cloudera.

**Comment by hahafamilia** [comment]
Hello, The same problem occurs for me.
It doesn't seem to be a problem with HTTPFS in Cloudera CDH.

I'am using Cloudera CDH 6.1.

/etc/td-agent/td-agent.conf
`<source>
  @type tail
  @id input_tail
  <parse>
    @type nginx
    expression /^(?<remote>[^ ]*) (?<host>[^ ]*) (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^\"]*?)(?: +\S*)?)?" (?<code>[^ ]*) (?<size>[^ ]*)(?: "(?<referer>[^\"]*)" "(?<agent>[^\"]*)"(?:\s+(?<http_x_forwarded_for>[^ ]+))?)?$/
    time_format %d/%b/%Y:%H:%M:%S %z
  </parse>
  path /var/log/nginx/access.log
  pos_file /var/log/td-agent/nginx.access.log.pos
  tag td.nginx.access
  read_from_head true
  @log_level debug
</source>

<match td.nginx.access>
  @type webhdfs
  httpfs true
  host myhttpfs.example.com
  port 14000
  path /tmp/fluentd/%Y%m%d/access.log
  username admin
  flush_interval 5s
</match>`

/var/log/td-agent.log
`
tail -2020-01-30 19:17:31 +0900 [warn]: #0 failed to communicate hdfs cluster, path: /tmp/fluentd/20200130/access.log
2020-01-30 19:17:31 +0900 [warn]: #0 failed to flush the buffer. retry_time=0 next_retry_seconds=2020-01-30 19:17:32 +0900 chunk="59d58c35c3f9c0fc061dabc8b3243994" error_class=WebHDFS::ServerError error="Failed to connect to host myhttpfs.example.com:14000, end of file reached"
  2020-01-30 19:17:31 +0900 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/webhdfs-0.8.0/lib/webhdfs/client_v1.rb:345:in `rescue in request'
  2020-01-30 19:17:31 +0900 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/webhdfs-0.8.0/lib/webhdfs/client_v1.rb:342:in `request'
  2020-01-30 19:17:31 +0900 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/webhdfs-0.8.0/lib/webhdfs/client_v1.rb:273:in `operate_requests'
  2020-01-30 19:17:31 +0900 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/webhdfs-0.8.0/lib/webhdfs/client_v1.rb:73:in `create'
  2020-01-30 19:17:31 +0900 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-webhdfs-1.2.4/lib/fluent/plugin/out_webhdfs.rb:274:in `rescue in send_data'
  2020-01-30 19:17:31 +0900 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-webhdfs-1.2.4/lib/fluent/plugin/out_webhdfs.rb:271:in `send_data'
  2020-01-30 19:17:31 +0900 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-webhdfs-1.2.4/lib/fluent/plugin/out_webhdfs.rb:389:in `block in write'
  2020-01-30 19:17:31 +0900 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-webhdfs-1.2.4/lib/fluent/plugin/out_webhdfs.rb:335:in `compress_context'
  2020-01-30 19:17:31 +0900 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-webhdfs-1.2.4/lib/fluent/plugin/out_webhdfs.rb:388:in `write'
  2020-01-30 19:17:31 +0900 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.7.4/lib/fluent/plugin/output.rb:1125:in `try_flush'
  2020-01-30 19:17:31 +0900 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.7.4/lib/fluent/plugin/output.rb:1431:in `flush_thread_run'
  2020-01-30 19:17:31 +0900 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.7.4/lib/fluent/plugin/output.rb:461:in `block (2 levels) in start'
  2020-01-30 19:17:31 +0900 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.7.4/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'                                                                                                  2020-01-30 19:17:34 +0900 [warn]: #0 failed to communicate hdfs cluster, path: /tmp/fluentd/20200130/access.log
2020-01-30 19:17:34 +0900 [warn]: #0 failed to flush the buffer. retry_time=1 next_retry_seconds=2020-01-30 19:17:35 +0900 chunk="59d58c35c3f9c0fc061dabc8b3243994" error_class=WebHDFS::ServerError error="Failed to connect to host myhttpfs.example.com:14000, end of file reached"
`


I get the above error.
So I tested HttpFS.
MKDIR and CREATE operations are successed.

`
curl -i -X PUT  \
"http://myhttpfs.example.com:14000/webhdfs/v1/tmp/fluentd/ymd=2020-01-30?op=MKDIRS&user.name=admin" ;
 
curl -i -X PUT -H "Content-Type: application/octet-stream" -d 'json={"action":"login", "user":2}'  \
"http://myhttpfs.example.com:14000/webhdfs/v1/tmp/fluentd/ymd=2020-01-30/access.log?op=CREATE&data=true&user.name=admin" ;
`

If the file exists in HDFS, log data is transferred.
