### ISSUE TITLE
the webhdfs doesn't work 

### ISSUE THREAD

**Issue by lingethan** [fluent/fluent-plugin-webhdfs#55]
I installed the fluentd as a pod in k8s, it doesn't send the log to hdfs side.

# My configuration like following
type tail 
path /webapp/gc.log 
pos_file /var/log/gc.log.pos 
tag hdfs.* 
format none 

type webhdfs 
host hdpnamenode1.synnex.org 
port 50070 
path /user/gc/gc.log 
flush_interval 10s 

**the exception like following**
 2017-04-27T10:01:45.730896711Z Successfully installed fluent-plugin-concat-1.0.0
2017-04-27T10:01:45.731062242Z Parsing documentation for fluent-plugin-concat-1.0.0
2017-04-27T10:01:45.731079854Z Installing ri documentation for fluent-plugin-concat-1.0.0
2017-04-27T10:01:45.731092461Z Done installing documentation for fluent-plugin-concat after 0 seconds
2017-04-27T10:01:45.731109494Z 1 gem installed
2017-04-27T10:01:47.411519959Z Successfully installed fluent-mixin-type-converter-0.1.0
2017-04-27T10:01:47.411600465Z Parsing documentation for fluent-mixin-type-converter-0.1.0
2017-04-27T10:01:47.411622561Z Installing ri documentation for fluent-mixin-type-converter-0.1.0
2017-04-27T10:01:47.411642680Z Done installing documentation for fluent-mixin-type-converter after 0 seconds
2017-04-27T10:01:47.411661294Z 1 gem installed
2017-04-27T10:01:48.170906896Z 2017-04-27 10:01:48 +0000 [info]: reading config file path="/etc/td-agent/td-agent.conf"
2017-04-27T10:01:48.172375632Z 2017-04-27 10:01:48 +0000 [info]: starting fluentd-0.12.31
2017-04-27T10:01:48.392819790Z 2017-04-27 10:01:48 +0000 [info]: gem 'fluent-mixin-config-placeholders' version '0.4.0'
2017-04-27T10:01:48.392882509Z 2017-04-27 10:01:48 +0000 [info]: gem 'fluent-mixin-plaintextformatter' version '0.2.6'
2017-04-27T10:01:48.392899368Z 2017-04-27 10:01:48 +0000 [info]: gem 'fluent-mixin-type-converter' version '0.1.0'
2017-04-27T10:01:48.392914610Z 2017-04-27 10:01:48 +0000 [info]: gem 'fluent-plugin-concat' version '1.0.0'
2017-04-27T10:01:48.392929221Z 2017-04-27 10:01:48 +0000 [info]: gem 'fluent-plugin-docker_metadata_filter' version '0.1.3'
2017-04-27T10:01:48.392944170Z 2017-04-27 10:01:48 +0000 [info]: gem 'fluent-plugin-elasticsearch' version '1.5.0'
2017-04-27T10:01:48.392958967Z 2017-04-27 10:01:48 +0000 [info]: gem 'fluent-plugin-kafka' version '0.4.1'
2017-04-27T10:01:48.392973337Z 2017-04-27 10:01:48 +0000 [info]: gem 'fluent-plugin-kubernetes_metadata_filter' version '0.24.0'
2017-04-27T10:01:48.392987985Z 2017-04-27 10:01:48 +0000 [info]: gem 'fluent-plugin-mongo' version '0.7.16'
2017-04-27T10:01:48.393391194Z 2017-04-27 10:01:48 +0000 [info]: gem 'fluent-plugin-rewrite-tag-filter' version '1.5.5'
2017-04-27T10:01:48.393441268Z 2017-04-27 10:01:48 +0000 [info]: gem 'fluent-plugin-s3' version '0.8.0'
2017-04-27T10:01:48.393457218Z 2017-04-27 10:01:48 +0000 [info]: gem 'fluent-plugin-scribe' version '0.10.14'
2017-04-27T10:01:48.393471668Z 2017-04-27 10:01:48 +0000 [info]: gem 'fluent-plugin-td' version '0.10.29'
2017-04-27T10:01:48.393485650Z 2017-04-27 10:01:48 +0000 [info]: gem 'fluent-plugin-td-monitoring' version '0.2.2'
2017-04-27T10:01:48.393499974Z 2017-04-27 10:01:48 +0000 [info]: gem 'fluent-plugin-webhdfs' version '0.4.2'
2017-04-27T10:01:48.393514193Z 2017-04-27 10:01:48 +0000 [info]: gem 'fluentd' version '0.12.31'
2017-04-27T10:01:48.393945922Z 2017-04-27 10:01:48 +0000 [info]: adding match pattern="hdfs.**" type="webhdfs" 
 2017-04-27T10:01:48.592082814Z /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/json-1.8.1/lib/json/version.rb:3: warning: already initialized constant JSON::VERSION
2017-04-27T10:01:48.592217181Z /opt/td-agent/embedded/lib/ruby/2.1.0/json/version.rb:3: warning: previous definition of VERSION was here
2017-04-27T10:01:48.592235104Z /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/json-1.8.1/lib/json/version.rb:4: warning: already initialized constant JSON::VERSION_ARRAY
2017-04-27T10:01:48.592255695Z /opt/td-agent/embedded/lib/ruby/2.1.0/json/version.rb:4: warning: previous definition of VERSION_ARRAY was here
2017-04-27T10:01:48.592276651Z /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/json-1.8.1/lib/json/version.rb:5: warning: already initialized constant JSON::VERSION_MAJOR
2017-04-27T10:01:48.592296117Z /opt/td-agent/embedded/lib/ruby/2.1.0/json/version.rb:5: warning: previous definition of VERSION_MAJOR was here
2017-04-27T10:01:48.592311493Z /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/json-1.8.1/lib/json/version.rb:6: warning: already initialized constant JSON::VERSION_MINOR
2017-04-27T10:01:48.592326563Z /opt/td-agent/embedded/lib/ruby/2.1.0/json/version.rb:6: warning: previous definition of VERSION_MINOR was here
2017-04-27T10:01:48.592344919Z /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/json-1.8.1/lib/json/version.rb:7: warning: already initialized constant JSON::VERSION_BUILD
2017-04-27T10:01:48.592365682Z /opt/td-agent/embedded/lib/ruby/2.1.0/json/version.rb:7: warning: previous definition of VERSION_BUILD was here
2017-04-27T10:01:48.599185531Z /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/json-1.8.1/lib/json/common.rb:99: warning: already initialized constant JSON::NaN
2017-04-27T10:01:48.599238535Z /opt/td-agent/embedded/lib/ruby/2.1.0/json/common.rb:99: warning: previous definition of NaN was here
2017-04-27T10:01:48.599257346Z /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/json-1.8.1/lib/json/common.rb:101: warning: already initialized constant JSON::Infinity
2017-04-27T10:01:48.599277726Z /opt/td-agent/embedded/lib/ruby/2.1.0/json/common.rb:101: warning: previous definition of Infinity was here
2017-04-27T10:01:48.599298477Z /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/json-1.8.1/lib/json/common.rb:103: warning: already initialized constant JSON::MinusInfinity
2017-04-27T10:01:48.599319034Z /opt/td-agent/embedded/lib/ruby/2.1.0/json/common.rb:103: warning: previous definition of MinusInfinity was here
2017-04-27T10:01:48.599338846Z /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/json-1.8.1/lib/json/common.rb:128: warning: already initialized constant JSON::UnparserError
2017-04-27T10:01:48.599356491Z /opt/td-agent/embedded/lib/ruby/2.1.0/json/common.rb:128: warning: previous definition of UnparserError was here
2017-04-27T10:01:48.956295741Z 2017-04-27 10:01:48 +0000 [error]: unexpected error error="No such file or directory - addr" 
 2017-04-27T10:01:48.956398014Z   2017-04-27 10:01:48 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/uuidtools-2.1.5/lib/uuidtools.rb:587:in ``'
2017-04-27T10:01:48.956419942Z   2017-04-27 10:01:48 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/uuidtools-2.1.5/lib/uuidtools.rb:587:in `ifconfig'
2017-04-27T10:01:48.956443039Z   2017-04-27 10:01:48 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/uuidtools-2.1.5/lib/uuidtools.rb:634:in `mac_address'
2017-04-27T10:01:48.956501706Z   2017-04-27 10:01:48 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/uuidtools-2.1.5/lib/uuidtools.rb:242:in `block in timestamp_create'
2017-04-27T10:01:48.956524635Z   2017-04-27 10:01:48 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/uuidtools-2.1.5/lib/uuidtools.rb:232:in `synchronize'
2017-04-27T10:01:48.956543399Z   2017-04-27 10:01:48 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/uuidtools-2.1.5/lib/uuidtools.rb:232:in `timestamp_create'
2017-04-27T10:01:48.956581659Z   2017-04-27 10:01:48 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-mixin-config-placeholders-0.4.0/lib/fluent/mixin/config_placeholders.rb:37:in `uuid_timestamp'
2017-04-27T10:01:48.956603841Z   2017-04-27 10:01:48 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-mixin-config-placeholders-0.4.0/lib/fluent/mixin/config_placeholders.rb:72:in `block (2 levels) in configure'
2017-04-27T10:01:48.956623894Z   2017-04-27 10:01:48 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-mixin-config-placeholders-0.4.0/lib/fluent/mixin/config_placeholders.rb:41:in `call'
2017-04-27T10:01:48.956646008Z   2017-04-27 10:01:48 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-mixin-config-placeholders-0.4.0/lib/fluent/mixin/config_placeholders.rb:41:in `block in replace'
2017-04-27T10:01:48.956700043Z   2017-04-27 10:01:48 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-mixin-config-placeholders-0.4.0/lib/fluent/mixin/config_placeholders.rb:41:in `each'
2017-04-27T10:01:48.956725693Z   2017-04-27 10:01:48 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-mixin-config-placeholders-0.4.0/lib/fluent/mixin/config_placeholders.rb:41:in `reduce'
2017-04-27T10:01:48.956745971Z   2017-04-27 10:01:48 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-mixin-config-placeholders-0.4.0/lib/fluent/mixin/config_placeholders.rb:41:in `replace' 
 2017-04-27T10:01:48.956766620Z   2017-04-27 10:01:48 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-mixin-config-placeholders-0.4.0/lib/fluent/mixin/config_placeholders.rb:96:in `block in configure'
2017-04-27T10:01:48.956787423Z   2017-04-27 10:01:48 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-mixin-config-placeholders-0.4.0/lib/fluent/mixin/config_placeholders.rb:105:in `call'
2017-04-27T10:01:48.956807572Z   2017-04-27 10:01:48 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-mixin-config-placeholders-0.4.0/lib/fluent/mixin/config_placeholders.rb:105:in `configure'
2017-04-27T10:01:48.956831800Z   2017-04-27 10:01:48 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-mixin-plaintextformatter-0.2.6/lib/fluent/mixin/plaintextformatter.rb:21:in `configure'
2017-04-27T10:01:48.956860704Z   2017-04-27 10:01:48 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-webhdfs-0.4.2/lib/fluent/plugin/out_webhdfs.rb:126:in `configure'
2017-04-27T10:01:48.956881164Z   2017-04-27 10:01:48 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.31/lib/fluent/agent.rb:133:in `add_match'
2017-04-27T10:01:48.956901588Z   2017-04-27 10:01:48 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.31/lib/fluent/agent.rb:64:in `block in configure'
2017-04-27T10:01:48.956936874Z   2017-04-27 10:01:48 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.31/lib/fluent/agent.rb:57:in `each'
2017-04-27T10:01:48.956957646Z   2017-04-27 10:01:48 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.31/lib/fluent/agent.rb:57:in `configure'
2017-04-27T10:01:48.956975671Z   2017-04-27 10:01:48 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.31/lib/fluent/root_agent.rb:86:in `configure'
2017-04-27T10:01:48.956993908Z   2017-04-27 10:01:48 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.31/lib/fluent/engine.rb:129:in `configure'
2017-04-27T10:01:48.957011728Z   2017-04-27 10:01:48 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.31/lib/fluent/engine.rb:103:in `run_configure' 
 2017-04-27T10:01:48.957029738Z   2017-04-27 10:01:48 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.31/lib/fluent/supervisor.rb:489:in `run_configure'
2017-04-27T10:01:48.957046703Z   2017-04-27 10:01:48 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.31/lib/fluent/supervisor.rb:160:in `block in start'
2017-04-27T10:01:48.957065439Z   2017-04-27 10:01:48 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.31/lib/fluent/supervisor.rb:366:in `call'
2017-04-27T10:01:48.957084106Z   2017-04-27 10:01:48 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.31/lib/fluent/supervisor.rb:366:in `main_process'
2017-04-27T10:01:48.957107124Z   2017-04-27 10:01:48 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.31/lib/fluent/supervisor.rb:339:in `block in supervise'
2017-04-27T10:01:48.957128219Z   2017-04-27 10:01:48 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.31/lib/fluent/supervisor.rb:338:in `fork'
2017-04-27T10:01:48.957152780Z   2017-04-27 10:01:48 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.31/lib/fluent/supervisor.rb:338:in `supervise'
2017-04-27T10:01:48.957173967Z   2017-04-27 10:01:48 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.31/lib/fluent/supervisor.rb:156:in `start'
2017-04-27T10:01:48.957193631Z   2017-04-27 10:01:48 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.31/lib/fluent/command/fluentd.rb:173:in `<top (required)>'
2017-04-27T10:01:48.957215585Z   2017-04-27 10:01:48 +0000 [error]: /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
2017-04-27T10:01:48.957233942Z   2017-04-27 10:01:48 +0000 [error]: /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
2017-04-27T10:01:48.957253502Z   2017-04-27 10:01:48 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.31/bin/fluentd:5:in `<top (required)>' 
 2017-04-27T10:01:48.957280724Z   2017-04-27 10:01:48 +0000 [error]: /opt/td-agent/embedded/bin/fluentd:23:in `load'
2017-04-27T10:01:48.957299073Z   2017-04-27 10:01:48 +0000 [error]: /opt/td-agent/embedded/bin/fluentd:23:in `<top (required)>'
2017-04-27T10:01:48.957337491Z   2017-04-27 10:01:48 +0000 [error]: /usr/sbin/td-agent:7:in `load'
2017-04-27T10:01:48.957358040Z   2017-04-27 10:01:48 +0000 [error]: /usr/sbin/td-agent:7:in `<main>'
2017-04-27T10:01:48.967118286Z 2017-04-27 10:01:48 +0000 [info]: process finished code=256
2017-04-27T10:01:48.967153519Z 2017-04-27 10:01:48 +0000 [warn]: process died within 1 second. exit.

**Comment by repeatedly** [comment]
This is known issue of uuidtools on container.
Maybe, need to backport removing config-placehodler change https://github.com/fluent/fluent-plugin-webhdfs/pull/49 to v0.12.

**Comment by lingethan** [comment]
Sorry, I use the fluentd-elasticsearch 1.22 in kubernetes, it's ok for elasticsearch, but it's not successful for hdfs. I think it's not easy to remove config-placehodler

**Comment by repeatedly** [comment]
Another way is fixing uuidtools itself but no response from author: https://github.com/sporkmonger/uuidtools/pull/39

**Comment by lingethan** [comment]
So, I have to install the flume to collect the data for hdfs. :( Thanks a lot!

**Comment by repeatedly** [comment]
np. We will fix the problem later.

**Comment by repeatedly** [comment]
Released v0.6.0. It should work on container.
