### ISSUE TITLE
Compression Snappy is not work.

### ISSUE THREAD

**Issue by JaeGeunBang** [fluent/fluent-plugin-webhdfs#73]
**/etc/td-agent/td-agent.conf**

```
<source>
  @type kafka_group
  brokers localhost:9092
  consumer_group test
  topics TEST
  add_prefix fluentd
  add_suffix log
  format json
  start_from_beginning false
</source>

<match fluentd.TEST.log>
  @type copy
  <store>
    @type webhdfs
    namenode localhost:50070

    path /user/test/%Y/%m/%d/%H/%M/test-%Y%m%d%H%M.log
    compress snappy

    <format>
      @type single_value
      add_newline false
      message_key message
    </format>

    <buffer>
      @type file
      path /data/td-agent
      flush_mode interval
      flush_interval 1s
    </buffer>
  </store>
</match>
```

**/var/log/td-agent/td-agent.log**

```
2020-05-29 09:44:56 +0900 [warn]: #0 failed to communicate hdfs cluster, path: /user/test/2020/05/29/09/44/test-202005290944.log.sz
2020-05-29 09:44:56 +0900 [warn]: #0 got unrecoverable error in primary and no secondary error_class=TypeError error="no implicit conversion from nil to integer"
  2020-05-29 09:44:56 +0900 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.10.2/lib/fluent/plugin/buffer/chunk.rb:180:in `copy_stream'
  2020-05-29 09:44:56 +0900 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.10.2/lib/fluent/plugin/buffer/chunk.rb:180:in `block in write_to'
  2020-05-29 09:44:56 +0900 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.10.2/lib/fluent/plugin/buffer/file_chunk.rb:171:in `open'
  2020-05-29 09:44:56 +0900 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.10.2/lib/fluent/plugin/buffer/chunk.rb:179:in `write_to'
  2020-05-29 09:44:56 +0900 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-webhdfs-1.2.4/lib/fluent/plugin/webhdfs_compressor_snappy.rb:20:in `compress'
  2020-05-29 09:44:56 +0900 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-webhdfs-1.2.4/lib/fluent/plugin/out_webhdfs.rb:333:in `compress_context'
  2020-05-29 09:44:56 +0900 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-webhdfs-1.2.4/lib/fluent/plugin/out_webhdfs.rb:388:in `write'
  2020-05-29 09:44:56 +0900 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.10.2/lib/fluent/plugin/output.rb:1133:in `try_flush'
  2020-05-29 09:44:56 +0900 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.10.2/lib/fluent/plugin/output.rb:1439:in `flush_thread_run'
  2020-05-29 09:44:56 +0900 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.10.2/lib/fluent/plugin/output.rb:461:in `block (2 levels) in start'
  2020-05-29 09:44:56 +0900 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.10.2/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2020-05-29 09:44:56 +0900 [warn]: #0 bad chunk is moved to /tmp/fluent/backup/worker0/object_3fd23738e570/5a6bec0edcd08f897fc647e296fac35b.log

```

I am using td-agent 3.7.1

The snappy gem was downloaded from ruby.gem (https://rubygems.org/gems/snappy). version is 0.0.17.

Messages stored in kafka are stored in JSON format. 

- ex. {"a": "a1", "b": "b1"}

I know that the current compression method supports gzip, snappy, bzip2, and lzo_command. I want to compress with snappy but I get the above error. I have confirmed that other compression methods (gzip, bzip2, lzo_command) work fine.

**Comment by tagomoris** [comment]
The stacktrace you showed is typically caused by the missing value for the specified key `message` of the `<format> @type single_value </format>` formatter.

I'm not sure why the other compressor can work well but snappy cannot, but the value conversion from `nil` could be the reason.
(Other compressors don't hit the problem about value conversion from `nil`?)

Are you sure that the record contains the `message` key and its value?
If so, can I see the value of the message key? (`copy` and `stdout` plugins should be helpful)

**Comment by JaeGeunBang** [comment]
Thank you for the reply.



I changed the `.conf` as below. Remove `<format> @type single_value </format>` formatter and add `<store> @type stdout </store>` for debugging.

```
<source>
  @type kafka_group
  brokers localhost:9092
  consumer_group test
  topics TEST
  add_prefix fluentd
  add_suffix log
  format json
  start_from_beginning false
</source>

<match fluentd.TEST.log>
  @type copy
  <store>
    @type stdout
  </store>
  
  <store>
    @type webhdfs
    namenode localhost:50070

    path /user/test/%Y/%m/%d/%H/%M/test-%Y%m%d%H%M.log
    compress snappy

    <buffer>
      @type file
      path /data/td-agent
      flush_mode interval
      flush_interval 1s
    </buffer>
  </store>
</match>
```



As a result of the test, it was confirmed that the output is as below.

```
2020-05-29 13:22:30.416036274 +0900 fluentd.TEST.log: {"date":"2020-05-29_13:12","topic":"test1","count":"0"}
2020-05-29 13:22:36.416878675 +0900 fluentd.TEST.log: {"date":"2020-05-29_13:12","topic":"test1","count":"3"}
2020-05-29 13:22:50.439255700 +0900 fluentd.TEST.log: {"date":"2020-05-29_13:12","topic":"test2","count":"3"}
2020-05-29 13:22:50.439408264 +0900 fluentd.TEST.log: {"date":"2020-05-29_13:12","topic":"test2","count":"0"}
2020-05-29 13:22:54 +0900 [warn]: #0 failed to communicate hdfs cluster, path: /user/test/2020/05/29/13/21/test-202005291321.log.sz
2020-05-29 13:22:54 +0900 [warn]: #0 got unrecoverable error in primary and no secondary error_class=TypeError error="no implicit conversion from nil to integer"
  2020-05-29 13:22:54 +0900 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.10.2/lib/fluent/plugin/buffer/chunk.rb:180:in `copy_stream'
  2020-05-29 13:22:54 +0900 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.10.2/lib/fluent/plugin/buffer/chunk.rb:180:in `block in write_to'
  2020-05-29 13:22:54 +0900 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.10.2/lib/fluent/plugin/buffer/file_chunk.rb:171:in `open'
  2020-05-29 13:22:54 +0900 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.10.2/lib/fluent/plugin/buffer/chunk.rb:179:in `write_to'
  2020-05-29 13:22:54 +0900 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-webhdfs-1.2.4/lib/fluent/plugin/webhdfs_compressor_snappy.rb:20:in `compress'
  2020-05-29 13:22:54 +0900 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-webhdfs-1.2.4/lib/fluent/plugin/out_webhdfs.rb:333:in `compress_context'
  2020-05-29 13:22:54 +0900 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-webhdfs-1.2.4/lib/fluent/plugin/out_webhdfs.rb:388:in `write'
  2020-05-29 13:22:54 +0900 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.10.2/lib/fluent/plugin/output.rb:1133:in `try_flush'
  2020-05-29 13:22:54 +0900 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.10.2/lib/fluent/plugin/output.rb:1439:in `flush_thread_run'
  2020-05-29 13:22:54 +0900 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.10.2/lib/fluent/plugin/output.rb:461:in `block (2 levels) in start'
  2020-05-29 13:22:54 +0900 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.10.2/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2020-05-29 13:22:54 +0900 [warn]: #0 bad chunk is moved to /tmp/fluent/backup/worker0/object_3f9075bed29c/5a6c1c8dcccdc1d38cbb85a0c4769670.log

```



When I change to a different format (gzip, bzip2, lzo_command), I can see that it is stored in hdfs successfully. But only Snappy does not work as above.

![Screenshot from 2020-05-29 13-26-32](https://user-images.githubusercontent.com/22383120/83221475-dd757580-a1b0-11ea-978e-cafc6416288b.png)

![Screenshot from 2020-05-29 13-26-39](https://user-images.githubusercontent.com/22383120/83221478-dea6a280-a1b0-11ea-8215-3c50f4a42b89.png)

**Comment by tagomoris** [comment]
Thanks for the follow-ups! But unfortunately, I can't find the clear cause of the failure now.
